name: 4.3 module example 1 CICD pipeline

# ici vous avez le déclencheur de votre pipeline;
# contrairement à Google Cloud Build, vous pouvez le configurer d'ici
on:
  push:
    branches: ["main"]

# les "jobs" sont les étapes de votre pipeline
jobs:

    # votre prémière étape, que vous pouvez nommer arbitrairement
    build:
        # on décrit le type de machine sur lequel on veut run une étape
        runs-on: ubuntu-latest
        steps:
            # nom complet de l'action GitHub qui permet de cloner le repo
            # https://github.com/marketplace?type=actions
            - uses: actions/checkout@v4
            - name: build
              # `run` avec le caractère `|` permet d'écrire plusieurs commandes à la suite
              run: |
                echo "BUILD"
                pip install -r requirements.txt
            

